git-debimport policykit-1_0.105-3.debian.tar.gz

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,23 +1,41 @@
 #!/usr/bin/make -f
 # -*- makefile -*-
 
-include /usr/share/cdbs/1/rules/debhelper.mk
-include /usr/share/cdbs/1/class/autotools.mk
-include /usr/share/cdbs/1/rules/patchsys-quilt.mk
-include /usr/share/cdbs/1/rules/utils.mk
+DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
 
-DEB_DH_MAKESHLIBS_ARGS_policykit-1 := -Xusr/lib/polkit-1/
+%:
+	dh $@
 
-DEB_CONFIGURE_EXTRA_FLAGS := --enable-gtk-doc \
-                             --enable-man-pages \
-                             --enable-introspection=no
+DPKG_GENSYMBOLS_CHECK_LEVEL=4
+export DPKG_GENSYMBOLS_CHECK_LEVEL
 
-DISTRO := $(shell lsb_release -is 2>/dev/null)
+override_dh_auto_configure:
+	dh_auto_configure -- \
+		--enable-gtk-doc \
+		--enable-man-pages \
+		--enable-introspection \
+		--disable-systemd \
+		--disable-examples \
+		--libexecdir=\$${prefix}/lib/policykit-1
 
-binary-install/policykit-1::
-	# when building for Ubuntu, allow the admin group, on Debian use sudo group
-	if [ "$(DISTRO)" = "Ubuntu" ]; then \
-	    /bin/echo -e "[Configuration]\nAdminIdentities=unix-group:admin" > debian/policykit-1/etc/polkit-1/localauthority.conf.d/51-ubuntu-admin.conf; \
-	elif [ "$(DISTRO)" = "Debian" ]; then \
+override_dh_auto_test:
+	# the system D-BUS tests can't work on the buildds, so don't let a
+	# failed test fail the build
+	make check || true
+
+override_dh_makeshlibs:
+	dh_makeshlibs -Xusr/lib/$(DEB_HOST_MULTIARCH)/polkit-1/
+
+override_dh_shlibdeps:
+	dh_shlibdeps
+	dh_girepository
+
+override_dh_install:
+	dh_install
+	# on Debian use sudo group; on Ubuntu, also allow the admin group for
+	# historical reasons
+	if dpkg-vendor --is ubuntu; then \
+	    /bin/echo -e "[Configuration]\nAdminIdentities=unix-group:sudo;unix-group:admin" > debian/policykit-1/etc/polkit-1/localauthority.conf.d/51-ubuntu-admin.conf; \
+	elif dpkg-vendor --is debian; then \
 	    /bin/echo -e "[Configuration]\nAdminIdentities=unix-group:sudo" > debian/policykit-1/etc/polkit-1/localauthority.conf.d/51-debian-sudo.conf; \
 	fi
